name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'network_config/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'network_config/**'
      - '.github/workflows/terraform.yml'

env:
  TF_LOG: INFO
  TF_INPUT: "false"
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is 
    # ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use repo secrets: Settings > Secrets and variables > Actions
      - name: Configure AWS credentials (keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        if: always()
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -out=tf.plan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: tf.plan
